### PR TITLE
Make sure embeddings don't fail

### LINKED ISSUE #118: Handle immediate faliure of embedding due to rate limit
Right now we are marking the source indexed with the model before we know about the rate limit. This makes it impossible to try again

### PR DESCRIPTION
**Pull request by Til7701**
- When documents are ready to be embedded, they are now added to an `EmbeddingBacklog`
- The `EmbeddingTaskExecutor` takes document from the `EmbeddingBacklog` and tries to embed them.
- If this fails, it tries again after some time.
- If it fails too many times in a row it waits longer and eventually stops the thread. This might be changed to stopping the application as a whole.

I also tested other methods to prevent hitting the rate limit. When we are using an embedding model with a larger context window, we may increase the batch size for requests and not the length of the actual documents. Thus, the chunks of test are not too large, and we still get a performance boost due to fewer calls to the model.

A database version of the `EmbeddingBacklog` may be implemented to avoid loosing data upon restart of the application.

### CODE REVIEW

File: src/main/java/de/uol/pgdoener/civicsage/business/embedding/EmbeddingBacklog.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
+package de.uol.pgdoener.civicsage.business.embedding;
+
+import java.util.Collection;
+import java.util.UUID;
+
+/**
+ * An EmbeddingBacklog is a queue-like structure that holds embedding tasks.
+ * Implementations of this interface should preserve the order of tasks
```
Comment (JayPi4c) [inline src/main/java/de/uol/pgdoener/civicsage/business/embedding/EmbeddingBacklog.java]: Why should they preserve the order? In my mind, a selective Backlog would be perfectly fine as well. It could be used as a priority list, ordering what resources need to be indexed first.

File: src/main/java/de/uol/pgdoener/civicsage/business/embedding/EmbeddingService.java [hunk 2]
```diff
@@ -52,4 +51,19 @@ public void delete(UUID sourceId) {
...
+    )
+    public Collection<UUID> getPendingSourceIds() {
+        return embeddingBacklog.getSourceIds();
+    }
+
+    @CacheEvict(
+            cacheNames = CachingConfig.SEARCH_CACHE_NAME,
+            allEntries = true
+    )
+    public void clearCache() {
```
Comment (JayPi4c) [inline src/main/java/de/uol/pgdoener/civicsage/business/embedding/EmbeddingService.java:83]: How silly, that the whole logic is done using a single annotation.

**Review by JayPi4c — COMMENTED** [review]
I like the current implementation and see the benefits. I see many problems, that are mitigated by this approach - including the rate limit - however, I don't like the general reasoning to primarily target the rate limit. Personally, I think the rate limit is not a concern of the backend but of the admin who is configuring the application. So if we hit the rate limit, we can give a log and move on. 
But again, this approach does handle more than simply the rate limit which is why I want this to be merged. As of now, however, I can't approve it, as I am not home to test the functionality in depth. (How does it handles loosing network connection or a non responsive llm?). I'll come back to this later this week.

File: src/main/java/de/uol/pgdoener/civicsage/business/embedding/EmbeddingBacklog.java (hunk 1 above)
Comment (Til7701) [reply src/main/java/de/uol/pgdoener/civicsage/business/embedding/EmbeddingBacklog.java]: I wanted to make sure, that we don't have to deal with starvation. Furthermore, it just seems fair that the first request to index something also gets embedded first. Thus users don't have to wait indefinitely.

I could modify the comment to better reflect those requirements.

**Comment by Til7701** [comment]
What is your opinion on the mechanism to handle too many failures?

**Comment by Til7701** [comment]
TODO

- [x] Handle deletion of source while embedding
- [x] Stagger bootstrap indexing

**Comment by JayPi4c** [comment]
> What is your opinion on the mechanism to handle too many failures?

What exactly are you referring to? The implementation as a whole or the `handleException` method in particular? On first glance, both seem ok.

**Comment by Til7701** [comment]
I am referring to the `handleException` method. So it's fine :)

**Review by JayPi4c — APPROVED** [review]
